### PR TITLE
Added 'extractCardId' to retrieve card id from pull request titles

### PR DESCRIPTION
**Pull request by JohnDMathis**
Added a new action "extractCardId" to make it easy for consumers to use a card id embedded in a pull request title. (Or really any  text string.)

Testing:
- `npm run test`
- Review the `tests.yml` workflow and the `getCardIdAndBlock` job, which tests the new extractCardId action.
- Make sure your test_payload.json has valid test values, and is updated with the `extractCardId` block as shown in the readme.
- `npm run act` to run all 3 test jobs, or `npm run act -- -j getCardIdAndBlock` to run only the new job.

### CODE REVIEW

**Comment by rniemeyer** [comment]
@JohnDMathis - Can we add the `extractCardId` action to the reference section of the README?

**Comment by JohnDMathis** [comment]
@rniemeyer updated!

**Comment by rniemeyer** [comment]
@JohnDMathis - there is some missing coverage on extractCardId (exception case).

**Comment by JohnDMathis** [comment]
@rniemeyer thank you! updated

**Pull request merged**
